title: Xium OS Documentation
description: AI-first Enterprise Data System
baseurl: ""
url: "https://docs.xium.ai"
favicon_ico: "/icons/icon.ico"

remote_theme: just-the-docs/just-the-docs

# Sprache / Language
lang: de

# Navigation
nav_sort: case_insensitive

# Aux links (oben rechts)
aux_links:
  "xium.ai":
    - "https://xium.ai"

# Footer
footer_content: "© 2026 Xium OS"

# Search
search_enabled: true
search_tokenizer_separator: /[\s\-_]+/

# Code highlighting
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

plugins:
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - "*.sh"
